# Dot in front of the job will hide it from the CI
.test_template:
  stage: test
  artifacts:
    paths:
      - tests/test_artifacts/  # Or the directory where plots are saved
    expire_in: 1 week  # Optional: set an expiration time for artifacts
    when: on_failure  # Save artifacts only on failure
  script: python -m pytest --verbose

.cpu_template:
  extends: .test_template
  image: mambaorg/micromamba:jammy
  before_script:
    - micromamba install -y -n base -c conda-forge "python=$PYTHON_VERSION"
    - python --version  # For debugging
    - pip install .[dev]

.gpu_template:
  extends: .test_template
  image: mambaorg/micromamba:jammy-cuda-12.3.1
  before_script:
    - micromamba install -y -n base -c conda-forge "python=$PYTHON_VERSION"
    - python --version  # For debugging
    - nvidia-smi  # Nvidia GPU information
    - pip install .[dev]
    # make sure PyTorch us using the GPUs
    - python -c "import torch; exit('PyTorch did not find a GPU') if not torch.cuda.is_available() else print('PyTorch is using GPU')"
  tags:
    - saas-linux-medium-amd64-gpu-standard


test_code_formatting:
  stage: .pre
  image: !reference [.cpu_template, image]
  before_script:
    - micromamba install -y -n base -c conda-forge 'python=3.11' git
    - git --version # make sure git in installed
    - git config --global --add safe.directory $(pwd)
    - python -m pip install pre-commit
    - pre-commit install
  script:
    - pre-commit run --all-files


test_py3_11_gpu:
  extends: .gpu_template
  variables:
    PYTHON_VERSION: "3.11"

test_py3_11_cpu:
  extends: .cpu_template
  variables:
    PYTHON_VERSION: "3.11"

test_py3_10_gpu:
  extends: .gpu_template
  variables:
    PYTHON_VERSION: "3.10"
  when: manual

test_py3_10_cpu:
  extends: .cpu_template
  variables:
    PYTHON_VERSION: "3.10"
  when: manual

test_py3_9_gpu:
  extends: .gpu_template
  variables:
    PYTHON_VERSION: "3.9"
  when: manual

test_py3_9_cpu:
  extends: .cpu_template
  variables:
    PYTHON_VERSION: "3.9"
  when: manual

test_py3_8_gpu:
  extends: .gpu_template
  variables:
    PYTHON_VERSION: "3.8"
  when: manual

test_py3_8_cpu:
  extends: .cpu_template
  variables:
    PYTHON_VERSION: "3.8"
  when: manual


docs:
  extends: .cpu_template
  script:
    - micromamba install -y -n base -c conda-forge make pandoc
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build

pages:
  # Take compiled html, and make available on gitlab pages
  # at neuralmag.gitlab.io/neuralmag
  stage: deploy
  variables:
    # The deploy job does not need the neuralmag sources.
    GIT_STRATEGY: none
  script:
    # gitlab pages will published everything in `public`
    - mkdir -p public
    - cp -a docs/_build/html/* public
  artifacts:
    paths:
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy.
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


# Defining workflow rules is required to avoid duplicated pipelines
# (https://docs.gitlab.com/ee/ci/jobs/job_rules.html#avoid-duplicate-pipelines).
# With the following rules, we only run the CI on the main branch,
# for open merge requests (but not for commits on different branches when no
# MR has been opened yet), when pushing tags, or when manually running a pipeline
# in the web interface.
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
